// Generated by CoffeeScript 1.9.0
(function() {
  var chalk, commander, configd, pkg,
    __slice = [].slice;

  commander = require('commander');

  chalk = require('chalk');

  configd = require('./configd');

  pkg = require('../package.json');

  module.exports = function() {
    return commander.version(pkg.version).action(function() {
      var args, destination, options, sources;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (!(args.length > 2)) {
        console.warn(chalk.yellow("  At least one source and one destination need to be provided!"));
        return process.exit(1);
      }
      sources = args.slice(0, -2);
      destination = args[args.length - 2];
      options = args[args.length - 1];
      return configd(sources, destination, options).then(function(merged) {
        console.log(chalk.green("  Source " + sources + " have merged into " + destination));
        return process.exit(0);
      })["catch"](function(err) {
        console.error(chalk.red("  " + err.message));
        return process.exit(2);
      });
    }).parse(process.argv);
  };

}).call(this);
