// Generated by CoffeeScript 1.9.0
(function() {
  var Promise, chalk, configd, fs, path, _, _readFile, _writeFile;

  chalk = require('chalk');

  Promise = require('bluebird');

  _ = require('lodash');

  path = require('path');

  fs = require('fs');

  Promise.promisifyAll(fs);

  _readFile = function(source) {
    return fs.readFileAsync(source, {
      encoding: 'UTF-8'
    }).then(function(data) {
      var ext;
      ext = path.extname(source).toLowerCase();
      switch (ext) {
        case '.json':
          data = JSON.parse(data);
          break;
        case '.js':
          data = eval(data);
          break;
        default:
          throw new Error("File extension " + ext + " is not supported now!");
      }
      return data;
    });
  };

  _writeFile = function(filename, data) {
    var dir;
    dir = path.dirname(filename);
    return fs.existsAsync(dir).then(function(exists) {
      if (exists) {
        return;
      }
      return fs.mkdirAsync(dir);
    }).then(function() {
      return fs.writeFileAsync(filename, data);
    });
  };

  module.exports = configd = function(sources, destination, options) {
    return Promise.all(sources.map(_readFile)).then(function(configs) {
      var config;
      config = configs.reduce(function(x, y) {
        return _.merge(x, y);
      });
      return _writeFile(destination, JSON.stringify(config, null, 2)).then(function() {
        return config;
      });
    });
  };

}).call(this);
