// Generated by CoffeeScript 1.9.0
(function() {
  var Promise, fs, request, requestAsync;

  fs = require('fs');

  Promise = require('bluebird');

  request = require('request');

  requestAsync = Promise.promisify(request);

  module.exports = {

    /**
     * Default router, read local files
     */
    local: function(source) {
      return fs.readFileAsync(source, {
        encoding: 'UTF-8'
      });
    },

    /**
     * Read remote file through ssh
     */
    ssh: function(source) {},

    /**
     * Read file from git
     */
    git: function(source) {},

    /**
     * Read from mongo database
     */
    mongo: function(source) {},

    /**
     * Read file from http service
     */
    http: function(source) {
      return requestAsync({
        url: source,
        method: 'GET',
        headers: {
          "User-Agent": "configd spider"
        }
      }).spread(function(res, body) {
        var _ref;
        if (!(res.statusCode >= 200 && res.statusCode < 300)) {
          throw new Error("bad request " + res.statusCode + " at " + source);
        }
        if (((_ref = res.headers['content-type']) != null ? _ref.indexOf('application/json') : void 0) > -1) {
          body = JSON.parse(body);
        }
        return body;
      });
    }
  };

}).call(this);
